name: BlockDynastyEconomy
main: net.blockdynasty.economy.spigot.BukkitImplementation.BlockDynastyEconomy
version: 1.3.4
author: federkone
description: A Jobs plugin for spigot servers!
load: STARTUP
api-version: 1.15
folia-supported: true
commands:
  linkedin:
    description: Abre panel de trabajos
    usage: /linkedin
    aliases: [laburos]